# Generated by Django 5.0.7 on 2024-07-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('spno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
